case XBOARD:  action.theType = PRINT;
	action.data.message = xstrdup("XBOARD");
	putAction(output,&action);
	break;
case PROTOVER:  action.theType = PRINT;
	action.data.message = xstrdup("PROTOVER");
	putAction(output,&action);
	break;
case ACCEPTED:  action.theType = PRINT;
	action.data.message = xstrdup("ACCEPTED");
	putAction(output,&action);
	break;
case REJECTED:  action.theType = PRINT;
	action.data.message = xstrdup("REJECTED");
	putAction(output,&action);
	break;
case NEW:  action.theType = PRINT;
	action.data.message = xstrdup("NEW");
	putAction(output,&action);
	break;
case FORCE:  action.theType = PRINT;
	action.data.message = xstrdup("FORCE");
	putAction(output,&action);
	break;
case TIME:  action.theType = PRINT;
	action.data.message = xstrdup("TIME");
	putAction(output,&action);
	break;
case QUIT:  action.theType = PRINT;
	action.data.message = xstrdup("QUIT");
	putAction(output,&action);
	break;
case PRINT:  action.theType = PRINT;
	action.data.message = xstrdup("PRINT");
	putAction(output,&action);
	break;
case VARIANT:  action.theType = PRINT;
	action.data.message = xstrdup("VARIANT");
	putAction(output,&action);
	break;
case RANDOM:  action.theType = PRINT;
	action.data.message = xstrdup("RANDOM");
	putAction(output,&action);
	break;
case GO:  action.theType = PRINT;
	action.data.message = xstrdup("GO");
	putAction(output,&action);
	break;
case PLAYOTHER:  action.theType = PRINT;
	action.data.message = xstrdup("PLAYOTHER");
	putAction(output,&action);
	break;
case WHITE:  action.theType = PRINT;
	action.data.message = xstrdup("WHITE");
	putAction(output,&action);
	break;
case BLACK:  action.theType = PRINT;
	action.data.message = xstrdup("BLACK");
	putAction(output,&action);
	break;
case LEVEL:  action.theType = PRINT;
	action.data.message = xstrdup("LEVEL");
	putAction(output,&action);
	break;
case SD:  action.theType = PRINT;
	action.data.message = xstrdup("SD");
	putAction(output,&action);
	break;
case ST:  action.theType = PRINT;
	action.data.message = xstrdup("ST");
	putAction(output,&action);
	break;
case OTIM:  action.theType = PRINT;
	action.data.message = xstrdup("OTIM");
	putAction(output,&action);
	break;
case USERMOVE:  action.theType = PRINT;
	action.data.message = xstrdup("USERMOVE");
	putAction(output,&action);
	break;
case MOVENOW:  action.theType = PRINT;
	action.data.message = xstrdup("MOVENOW");
	putAction(output,&action);
	break;
case PING:  action.theType = PRINT;
	action.data.message = xstrdup("PING");
	putAction(output,&action);
	break;
case DRAW:  action.theType = PRINT;
	action.data.message = xstrdup("DRAW");
	putAction(output,&action);
	break;
case RESULT:  action.theType = PRINT;
	action.data.message = xstrdup("RESULT");
	putAction(output,&action);
	break;
case SETBOARD:  action.theType = PRINT;
	action.data.message = xstrdup("SETBOARD");
	putAction(output,&action);
	break;
case EDIT:  action.theType = PRINT;
	action.data.message = xstrdup("EDIT");
	putAction(output,&action);
	break;
case HINT:  action.theType = PRINT;
	action.data.message = xstrdup("HINT");
	putAction(output,&action);
	break;
case BK:  action.theType = PRINT;
	action.data.message = xstrdup("BK");
	putAction(output,&action);
	break;
case UNDO:  action.theType = PRINT;
	action.data.message = xstrdup("UNDO");
	putAction(output,&action);
	break;
case REMOVE:  action.theType = PRINT;
	action.data.message = xstrdup("REMOVE");
	putAction(output,&action);
	break;
case HARD:  action.theType = PRINT;
	action.data.message = xstrdup("HARD");
	putAction(output,&action);
	break;
case EASY:  action.theType = PRINT;
	action.data.message = xstrdup("EASY");
	putAction(output,&action);
	break;
case POST:  action.theType = PRINT;
	action.data.message = xstrdup("POST");
	putAction(output,&action);
	break;
case NOPOST:  action.theType = PRINT;
	action.data.message = xstrdup("NOPOST");
	putAction(output,&action);
	break;
case ANALYZE:  action.theType = PRINT;
	action.data.message = xstrdup("ANALYZE");
	putAction(output,&action);
	break;
case NAME:  action.theType = PRINT;
	action.data.message = xstrdup("NAME");
	putAction(output,&action);
	break;
case RATING:  action.theType = PRINT;
	action.data.message = xstrdup("RATING");
	putAction(output,&action);
	break;
case ICS:  action.theType = PRINT;
	action.data.message = xstrdup("ICS");
	putAction(output,&action);
	break;
case COMPUTER:  action.theType = PRINT;
	action.data.message = xstrdup("COMPUTER");
	putAction(output,&action);
	break;
